name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
    container: rust:bullseye

    steps:
    - uses: actions/checkout@v4
    - name: Prepare
      run: apt update && apt install -y libudev-dev
    - name: Build
      uses: actions-rs/cargo@v1
      with:
        command: build
